version: 2
jobs:
  flake8:
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout
      - run:
          command: |
            pip install setuptools tox virtualenv
      - run:
          command: |
            tox -e flake8
  readme:
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout
      - run:
          command: |
            pip install setuptools tox virtualenv
      - run:
          command: |
            tox -e readme
  sphinx:
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout
      - run:
          command: |
            pip install setuptools tox virtualenv
      - run:
          command: |
            tox -e sphinx
  tests:
    docker:
      - image: cimg/python:3.9.8
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_PASSWORD: ticketoffice
          POSTGRES_USER: ticketoffice
          POSTGRES_DB: ticketoffice
    steps:
      - checkout
      - run:
          command: |
            pip install setuptools tox virtualenv
      - run:
          command: |
            tox -e py39-dj{2x,30,31,3x}

workflows:
  version: 2
  default:
    jobs:
      - flake8
      - readme
      - sphinx
      - tests
