# Generated by Django 1.9.13 on 2017-04-25 14:33

import django.contrib.auth.hashers
from django.db import migrations, models
import functools
import uuid

from django_ticketoffice.compat import JSONField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('password', models.CharField(default=functools.partial(django.contrib.auth.hashers.make_password, *(None,), **{}), max_length=255)),
                ('place', models.CharField(blank=True, db_index=True, max_length=50)),
                ('purpose', models.CharField(blank=True, db_index=True, max_length=50)),
                ('data', JSONField(blank=True, default=dict, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expiry_datetime', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('usage_datetime', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
            ],
        ),
    ]
